_base_: "isaaclab_pickplace_base.yaml"

algo: "SAC"
policy_type: "Gaussian"
alpha: 0.2
automatic_entropy_tuning: false
tau: 0.005

replay_size: 200000
batch_size: 256
start_steps: 2048
updates_per_step: 1
target_update_interval: 1
