_base_: "isaaclab_pickplace_base.yaml"

algo: "OBAC"
alpha: 0.2
automatic_entropy_tuning: true
tau: 0.005
target_update_interval: 1
quantile: 0.9
bc_weight: 0.1

replay_size: 200000
batch_size: 256
start_steps: 2048
updates_per_step: 1
