_base_: "isaaclab_pickplace_base.yaml"

algo: "PPO"
clip_param: 0.2
ppo_epoch: 4
num_mini_batch: 4
value_loss_coef: 0.5
entropy_coef: 0.01
max_grad_norm: 0.5
gae_lambda: 0.95

rollout_steps: 256
lr: 0.0003
gamma: 0.99
hidden_size: 256

checkpoint:
  strategies:
    - "latest"
    - "best"
  interval_epochs: 25
  save_buffer: false
